#
# Makefile
# ronan, 2013-11-01 23:51
#

all:
	#@echo "compiling hello..."
	#gcc hello.c -o hello
	#./hello
	#@echo "compiling exercice1..."
	#gcc exercice1.c -o exercice1
	#./exercice1
	#@echo "compiling exercice2..."
	#gcc exercice2.c -o exercice2
	#./exercice2
	#@echo "compiling exercice3..."
	#gcc exercice3.c -o exercice3
	#./exercice3
	@echo "compiling exercice4..."
	gcc exercice4.c -o exercice4
	./exercice4

# vim:ft=make
