parameters:
#    ronan_guilloux_o_auth.example.class: RonanGuilloux\OAuthBundle\Example

services:
#    ronan_guilloux_o_auth.example:
#        class: %ronan_guilloux_o_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
